let config, token, profiles=[], founderSlots=[];
const statusEl=document.getElementById("admin-status");
const escapeHtml=(value)=>String(value??"").replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
async function refreshToken(){const refresh=localStorage.getItem("bewlet_supabase_refresh_token");if(!refresh)return null;const response=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:config.supabasePublishableKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:refresh})});if(!response.ok)return null;const session=await response.json();localStorage.setItem("bewlet_supabase_access_token",session.access_token);if(session.refresh_token)localStorage.setItem("bewlet_supabase_refresh_token",session.refresh_token);return session.access_token}
async function api(path="",options={}){let response=await fetch(`/api/account${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{}),Authorization:`Bearer ${token}`}});if(response.status===401){token=await refreshToken();if(!token)return location.replace("/?login=required");response=await fetch(`/api/account${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{}),Authorization:`Bearer ${token}`}})}const data=await response.json();if(!response.ok)throw new Error(data.error||"Admin request failed");return data}
function paymentAmount(payment){return payment.currency==="USD"?`US$${(Number(payment.amount_minor)/100).toFixed(2)}`:`Rp${Number(payment.amount_minor).toLocaleString()}`}
function isActive(profile){return Boolean(profile.last_sign_in_at&&Date.now()-new Date(profile.last_sign_in_at).getTime()<=30*86400000)}
function render(){const filter=document.getElementById("admin-filter").value;const search=document.getElementById("admin-search").value.trim().toLowerCase();const matches=(profile)=>filter==="all"||(filter==="active"?profile.status==="approved"&&isActive(profile):["ID","INTL"].includes(filter)?profile.pricing_region===filter:profile.status===filter);const visible=profiles.filter((profile)=>matches(profile)&&(!search||`${profile.display_name||""} ${profile.email}`.toLowerCase().includes(search)));document.getElementById("pending-count").textContent=profiles.filter((p)=>p.status==="pending").length;document.getElementById("approved-count").textContent=profiles.filter((p)=>p.status==="approved").length;document.getElementById("active-count").textContent=profiles.filter((p)=>p.status==="approved"&&isActive(p)).length;const idSlot=founderSlots.find((slot)=>slot.region==="ID");const intlSlot=founderSlots.find((slot)=>slot.region==="INTL");document.getElementById("id-founder-count").textContent=`${idSlot?.claimed||0}/${idSlot?.capacity||100}`;document.getElementById("intl-founder-count").textContent=`${intlSlot?.claimed||0}/${intlSlot?.capacity||100}`;document.getElementById("admin-list").innerHTML=visible.length?visible.map((p)=>`<article class="account-row"><div><h3>${escapeHtml(p.display_name||p.email)}</h3><div class="account-meta"><span>${escapeHtml(p.email)}</span><span class="badge">${escapeHtml(p.status)}</span><span>${escapeHtml(p.pricing_region)}</span><span>Registered ${new Date(p.created_at).toLocaleDateString()}</span>${p.last_sign_in_at?`<span>Last active ${new Date(p.last_sign_in_at).toLocaleDateString()}</span>`:""}</div>${p.payment?.signed_url?`<a class="proof" href="${escapeHtml(p.payment.signed_url)}" target="_blank" rel="noopener">View payment proof · ${paymentAmount(p.payment)}</a>`:'<div class="proof">No payment proof submitted</div>'}</div><div class="account-actions">${p.status==="pending"?`<button class="approve" onclick="review('${p.id}','approved')">Approve</button><button class="reject" onclick="review('${p.id}','rejected')">Reject</button>`:""}${p.status==="approved"?`<button class="suspend" onclick="review('${p.id}','suspended')">Suspend</button>`:""}${["rejected","suspended"].includes(p.status)?`<button class="restore" onclick="review('${p.id}','approved')">Restore access</button>`:""}</div></article>`).join(""):'<div class="empty">No accounts match this view.</div>'}
async function load(){statusEl.textContent="Loading accounts…";try{const data=await api("?action=admin-list");profiles=data.profiles||[];founderSlots=data.founderSlots||[];render();statusEl.textContent=`${profiles.length} total account${profiles.length===1?"":"s"}${data.warnings?.length?` · Setup warning: ${data.warnings.join(" | ")}`:""}` }catch(error){statusEl.textContent=error.message}}
window.review=async(userId,decision)=>{const reason=["rejected","suspended"].includes(decision)?prompt(`Reason for ${decision}:`)||`Account ${decision}`:"";if(!confirm(`${decision.charAt(0).toUpperCase()+decision.slice(1)} this account?`))return;try{await api("",{method:"POST",body:JSON.stringify({action:"review",userId,decision,reason})});await load()}catch(error){statusEl.textContent=error.message}};
document.getElementById("admin-search").addEventListener("input",render);document.getElementById("admin-filter").addEventListener("change",render);document.querySelectorAll("[data-admin-view]").forEach((button)=>button.addEventListener("click",()=>{document.getElementById("admin-filter").value=button.dataset.adminView;render()}));document.getElementById("admin-refresh").addEventListener("click",load);document.getElementById("admin-signout").addEventListener("click",async()=>{if(token)await fetch(`${config.supabaseUrl}/auth/v1/logout`,{method:"POST",headers:{apikey:config.supabasePublishableKey,Authorization:`Bearer ${token}`}}).catch(()=>{});localStorage.removeItem("bewlet_supabase_access_token");localStorage.removeItem("bewlet_supabase_refresh_token");location.replace("/")});
config=await fetch("/api/public-config",{cache:"no-store"}).then((r)=>r.json());token=localStorage.getItem("bewlet_supabase_access_token")||await refreshToken();if(!token)location.replace("/?login=required");else{const sessionResponse=await fetch("/api/session",{headers:{Authorization:`Bearer ${token}`}});const session=sessionResponse.ok?await sessionResponse.json():null;if(!sessionResponse.ok)location.replace("/?login=required");else if(!session.admin)location.replace("/app");else load()}
